version: '2'
services:
    gitlab:
        image: 'gitlab/gitleb-ce:12.1.3-ce.0'
        restart: unless-stopped
        hostname: '10.10.10.98' # 指定节点 ip
        environment:
          TZ: 'Asia/Shanghai'
          GITLAB_OMNIBUS_CONFIG: |
            external_url 'http://10.10.10.98'
            gitlab_rails['time_zone'] = 'Asia/Shanghai'
            gitlab_rails['gitlab_shell_ssh_port'] = 54322
            postgresql['enable'] = false
            gitlab_rails['db_adapter'] = "postgresql"
            gitlab_rails['db_encoding'] = "utf8"
            gitlab_rails['db_database'] = "gitlabtest"
            gitlab_rails['db_username'] = "postgres"
            gitlab_rails['db_password'] = "postgres"
            gitlab_rails['db_host'] = "10.10.10.98"
            gitlab_rails['db_port'] = 5432
        ports:
            - '8080:80'
            - '843:443'
            - '54322:22'
        volumes:
            - '/opt/nfs/gitlab01:/etc/gitlab' # 以下三个文件需要单独创建，放在 nas 上保证
            - '/opt/nfs/gitlab01/log:/var/log/gitlab'
            - '/opt/nfs/gitlab01/opt:/var/opt/gitlab'
